# Generated by Django 3.1.6 on 2021-02-10 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=200, null=True)),
                ('opening_qty', models.IntegerField(blank=True, null=True)),
                ('added_qty', models.IntegerField(blank=True, null=True)),
                ('issued_dispatched_qty', models.IntegerField(blank=True, null=True)),
                ('reserve_qty', models.IntegerField(blank=True, null=True)),
                ('balanced_qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=400)),
                ('finish_type', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(max_length=300)),
                ('qty', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order', models.CharField(max_length=400)),
                ('customer_name', models.CharField(max_length=400)),
                ('order_date', models.DateField()),
                ('project', models.CharField(blank=True, max_length=400, null=True)),
                ('item_code', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1000)),
                ('order_qty', models.IntegerField()),
                ('order_type', models.CharField(blank=True, max_length=100, null=True)),
                ('delivered_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('amount_to_deliver', models.IntegerField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('projected', models.IntegerField(blank=True, null=True)),
                ('item_delivery_date', models.DateField(blank=True, null=True)),
                ('delay_days', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=400, null=True)),
                ('description_b', models.CharField(blank=True, max_length=1000, null=True)),
                ('item_group', models.CharField(blank=True, max_length=400, null=True)),
                ('warehouse', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(blank=True, max_length=1000, null=True)),
                ('remaining_days_delivery', models.IntegerField(blank=True, null=True)),
                ('payment_staus', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=200, null=True)),
                ('total_processed_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('partially_dispatched_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('latest_partially_dispatched_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('latest_partially_dispatched_date', models.DateField(blank=True, null=True)),
                ('qty_in_engineering', models.IntegerField(blank=True, default=0, null=True)),
                ('qty_in_buffing', models.IntegerField(blank=True, default=0, null=True)),
                ('qty_in_provisionally_schedule', models.IntegerField(blank=True, default=0, null=True)),
                ('qty_in_plating', models.IntegerField(blank=True, default=0, null=True)),
                ('qty_in_4sbuffing', models.IntegerField(blank=True, default=0, null=True)),
                ('qty_in_laquer', models.IntegerField(blank=True, default=0, null=True)),
                ('qty_in_packaging', models.IntegerField(blank=True, default=0, null=True)),
                ('latest_packaging_date', models.DateField(blank=True, null=True)),
                ('total_packaged_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('cumulated_invoice_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('latest_invoice_date', models.DateField(blank=True, null=True)),
                ('remaining_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('for_dispatch', models.IntegerField(default=0)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionalSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provision_date', models.DateField()),
                ('final_date', models.DateField(blank=True, null=True)),
                ('qty', models.IntegerField()),
                ('is_finalised', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_material_required', models.BooleanField(default=False)),
                ('from_inventory', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_data', to='mainApp.job')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_data', to='mainApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='StockRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=200, null=True)),
                ('required_qty', models.IntegerField(blank=True, null=True)),
                ('stock_category', models.CharField(blank=True, max_length=500, null=True)),
                ('po_number', models.CharField(blank=True, max_length=300, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=500, null=True)),
                ('stock_inward_estimate_date', models.DateField(blank=True, null=True)),
                ('latest_stock_inward_actual_date', models.DateField(blank=True, null=True)),
                ('recieved_qty', models.IntegerField(blank=True, null=True)),
                ('pending_qty', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('remaining_days', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDetails', to='mainApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=200, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_data_txn', to='mainApp.inventory')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_data_txn', to='mainApp.job')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_data_txn', to='mainApp.order')),
                ('provision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provision_data_txn', to='mainApp.provisionalschedule')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_data_txn', to='mainApp.stockrequirement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='provisionalschedule',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_required', to='mainApp.stockrequirement'),
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.order'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=200)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='mainApp.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
