# Generated by Django 2.0.2 on 2021-01-29 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tansaction_id', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_data_txn', to='mainApp.Job'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_data_txn', to='mainApp.Order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_data_txn', to='mainApp.ProvisionalSchedule'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data_txn', to='mainApp.StockRequirement'),
        ),
    ]
