# Generated by Django 2.0.2 on 2021-01-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='item_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='qty',
            new_name='order_qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
    ]
