# Generated by Django 2.0.2 on 2021-01-29 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210129_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_data_txn', to='mainApp.Job'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_data_txn', to='mainApp.Order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provision_data_txn', to='mainApp.ProvisionalSchedule'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_data_txn', to='mainApp.StockRequirement'),
        ),
    ]
