# Generated by Django 2.0.2 on 2021-01-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20210129_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
