# Generated by Django 2.0.2 on 2021-01-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20210120_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=200, null=True)),
                ('opening_qty', models.IntegerField(blank=True, null=True)),
                ('added_qty', models.IntegerField(blank=True, null=True)),
                ('issued_dispatched_qty', models.IntegerField(blank=True, null=True)),
                ('balanced_qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
