# Generated by Django 2.0.2 on 2021-01-21 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=400, null=True)),
                ('required_qty', models.IntegerField(blank=True, null=True)),
                ('stock_category', models.CharField(blank=True, max_length=500, null=True)),
                ('po_number', models.CharField(blank=True, max_length=300, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=500, null=True)),
                ('stock_inward_estimate_date', models.DateField(blank=True, null=True)),
                ('latest_stock_inward_actual_date', models.DateField(blank=True, null=True)),
                ('recieved_qty', models.IntegerField(blank=True, null=True)),
                ('pending_qty', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDetails', to='mainApp.Order')),
            ],
        ),
    ]
