# Generated by Django 2.0.2 on 2021-01-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20210129_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tansaction_id',
            new_name='transaction_id',
        ),
    ]
