# Generated by Django 2.0.2 on 2021-01-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20210129_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequirement',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrequirement',
            name='remaining_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
