# Generated by Django 2.0.2 on 2021-01-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=400)),
                ('finish_type', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(max_length=300)),
                ('qty', models.IntegerField()),
                ('date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Order')),
            ],
        ),
    ]
