# Generated by Django 2.0.2 on 2021-02-03 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionalschedule',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_data', to='mainApp.Job'),
        ),
    ]
