# Generated by Django 2.0.2 on 2021-01-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20210123_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latest_partially_dispatched_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
