# Generated by Django 2.0.2 on 2021-01-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_remove_stockrequirement_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequirement',
            name='item_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
