# Generated by Django 2.0.2 on 2021-01-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_stockrequirement_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reserve_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
