# Generated by Django 2.0.2 on 2021-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_provisionalschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='for_dispatch',
            field=models.IntegerField(default=0),
        ),
    ]
