# Generated by Django 2.0.2 on 2021-01-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_order_for_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalschedule',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_required', to='mainApp.StockRequirement'),
        ),
    ]
