# Generated by Django 2.0.2 on 2021-01-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_provisionalschedule_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalschedule',
            name='is_material_required',
            field=models.BooleanField(default=False),
        ),
    ]
