# Generated by Django 2.0.2 on 2021-01-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_provisionalschedule_is_material_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalschedule',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
