# Generated by Django 2.0.2 on 2021-01-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_order_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalschedule',
            name='from_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
