# Generated by Django 2.0.2 on 2021-01-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_provisionalschedule_from_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalschedule',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
